### ISSUE TITLE
Avoid Cross-Origin Read Blocking (CORB) 

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#1]
In reference to https://github.com/clarity-h2020/scenario-analysis/issues/11

Headers returned by EMIKAT REST API:
```
HTTP/1.1 200 OK
Date: Fri, 15 Mar 2019 13:42:51 GMT
Server: Apache-Coyote/1.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: origin, content-type, accept, authorization
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, DELETE, PUT, DELETE, OPTIONS, HEAD
Content-Type: application/json
Content-Length: 3042
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```

According to [this article](https://www.chromium.org/Home/chromium-security/corb-for-developers) you have to add an additional header: `X-Content-Type-Options: nosniff`.

**Comment by humerh** [comment]
I have implemented this additional option: "X-Content-Type-Options →nosniff"

Please verify it.

**Comment by p-a-s-c-a-l** [comment]
It works! Thanks, Heinrich!

**Comment by p-a-s-c-a-l** [comment]
I'm not able to download CSV files from EMIKAT API with Chrome:

``
Access to fetch at 'https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/csv?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
``

Strange enough, it *does* work with JSON and GeoJSON files.

**Comment by p-a-s-c-a-l** [comment]
Those are the headers return by the [CSV GET request](https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2974/table/csv?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27):
```
Connection: Keep-Alive
Content-Disposition: attachment; filename=report_1571997669660.csv
Content-Type: text/csv
Date: Fri, 25 Oct 2019 10:01:09 GMT
Keep-Alive: timeout=5, max=99
Server: Apache-Coyote/1.1
Transfer-Encoding: chunked
```

Those are the headers returned by a JSON/GeoJSON GET request:
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: origin, content-type, accept, authorization
Access-Control-Allow-Methods: GET, POST, DELETE, PUT, DELETE, OPTIONS, HEAD
Access-Control-Allow-Origin: *
Allow: HEAD,GET,OPTIONS
Connection: Keep-Alive
Content-Length: 1641
Content-Type: application/vnd.sun.wadl+xml
Date: Fri, 25 Oct 2019 10:01:09 GMT
Keep-Alive: timeout=5, max=100
Last-modified: Fr, 25 Okt 2019 12:01:09 MESZ
Server: Apache-Coyote/1.1
X-Content-Type-Options: nosniff
```

@humerh Can you please add the `Access-Control-Allow-` and `X-Content-Type-Options` to the CSV response, too?

**Comment by humerh** [comment]
Yes, I found the problem. The export in CSV has been solved in another way, and there I did not implement all the headers.
I added it alread in my code and on monday I will deploy the software.

**Comment by p-a-s-c-a-l** [comment]
done
