### ISSUE TITLE
Support Hazards with Local Effects [HC-LE API]

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#12]
This is related to the [calculation of tmrt](https://github.com/clarity-h2020/local-effects/issues/8).

Hazards with local effects /currently (tmrt based on [Heat Wave Events](https://github.com/clarity-h2020/csis/issues/57)) are (re-)calculated in EMIKAT and will be shown on the  [HC-LE Map](https://github.com/clarity-h2020/map-component/issues/34) and eventually in the [HC-LE Table](https://github.com/clarity-h2020/table-components/issues/2).

The API would probably expect just two parameters: 
- `$studyArea` or, if the study is already [initialised](https://github.com/clarity-h2020/emikat/issues/6), just the '$studyId'
- `$hazardEvents[]` See [this comment](https://github.com/clarity-h2020/data-package/issues/11#issuecomment-507262847) for the related explanation.

That means, in contrast to previous ideas, we don't need parameters for RCP and time period because we force the user in the [Scenario Selection UI](https://github.com/clarity-h2020/docker-drupal/issues/58) (probably better called *Event* Selection UI) to chose one event from the baseline and one corresponding event of the same type (frequent, occasional, rare) from the future.

In principle, the API then returns the two HC-LE layers (tmrt) related to the two events chosen by the user. Atm, the implementation of the  [HC-LE Table](https://github.com/clarity-h2020/table-components/issues/2) is on hold, so we are currently just in need of  a WMS Endpoint for the map.

The respective [HC-LE Data Package Resource](https://github.com/clarity-h2020/data-package/issues/11#issuecomment-506661274) has to be updated accordingly and example request / response URLs have to be [added to the Wiki](https://github.com/clarity-h2020/csis/issues/61).

**Comment by p-a-s-c-a-l** [comment]
> Now the result of Local effect calculation is also available as WMS-Maps:
> 
> https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aview.2974&bbox=4672000.0%2C1979500.0%2C4687500.0%2C1988000.0&width=768&height=421&srs=EPSG%3A3035&format=image%2Fgif&CQL_FILTER=PROJECT%3DBASELINE%20and%20PERIOD=%27Baseline%27%20AND%20RCP=%27Baseline%27%20AND%20FREQUENCE=%27Rare%27%20AND%20SZ_ID=2846&styles=T_A
> 
> In this link you can adapt the follwing parameters:
> 
> PROJECT=BASELINE ... (for future selection of an alternative ADAPTATION variants)
> PERIOD='Baseline' ... (Alternatives are: '20110101-20401231', '20410101-20701231' and '20710101-21001231')
> RCP='Baseline' ... (Alternatives are: 'rcp26', 'rcp45' and 'rcp85')
> FREQUENCE='Rare' ... (Alternatives are: 'Occassional' or 'Frequent')
> 
> @p-a-s-c-a-l , @therter please test and give me feedback, if this approach is ok.
> 
> SZ_ID=2846 has to be set to the current $emikatID
> 
> styles=T_A for Apparent temparature
> styles=T_TMRT for Mean Radiant Temperature
> styles=T_UTCI for UTCI Temperature
> 
> The color schemas (STYLE colors) are currently fixed but not optimized !!!!

**Comment by p-a-s-c-a-l** [comment]
Thanks. And what about the the JSON API needed for the [Table Component](https://github.com/clarity-h2020/table-components/issues/2)?

**Comment by humerh** [comment]
Do you mean the grid results as "JSON API"?
or 
the content of the "Summary table"?
If you mean the "Summary table" I need to understand, how this numbers are calculated. I need more information!

**Comment by p-a-s-c-a-l** [comment]
any kind of tabular data would be fine atm.

**Comment by humerh** [comment]
Ok, you can also get the HW Local effect results direct by emikat Rest interface:

As JSON:
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2974/table/data?rownum=10000&filter=PROJECT%3DBASELINE&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846

As CSV: 
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2974/table/csv?rownum=10000&filter=PROJECT%3DBASELINE&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846

or as GeoJSON
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2974/table/geojson?rownum=10000&filter=PROJECT%3DBASELINE&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846

**Comment by DenoBeno** [comment]
I presume this has been resolved now?

**Comment by p-a-s-c-a-l** [comment]
No HC_LE Data seems to be available for [this study](
https://csis.myclimateservice.eu/study/35/step/1449/view/table) (AgiosDimitrios): https://service.emikat.at/EmiKatTst/api/scenarios/3189/feature/view.2974/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27BASELINE%27&filter=TIME_PERIOD%3D%27Baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27Rare%27&filter=SZ_ID%3D3189

**Comment by p-a-s-c-a-l** [comment]
Same for [this study](https://csis.myclimateservice.eu/study/33/step/1455/view/table): https://service.emikat.at/EmiKatTst/api/scenarios/3209/feature/view.2974/table/data?rownum=1000&filter=STUDY_VARIANT%3D%27variant:baseline%27&filter=TIME_PERIOD%3D%27period:baseline%27&filter=EMISSIONS_SCENARIO%3D%27Baseline%27&filter=EVENT_FREQUENCY%3D%27frequency:frequent%27&filter=SZ_ID%3D3209

**Comment by DenoBeno** [comment]
As discussed earlier today, we have a workaround for the missing insolation data, so this should soon work for all locations. Technically it's already working for a few locations...

**Comment by p-a-s-c-a-l** [comment]
I assume this is working now and the issue can be closed?

**Comment by humerh** [comment]
Yes!
