### ISSUE TITLE
"Include in Report" functionality is blocked by CORS policy

### ISSUE THREAD

**Issue by therter** [clarity-h2020/emikat#14]
Please, add the Access-Control-Allow-Origin header to the wms, because at the moment we get the following error, when an image of a map with overlay layers from emikat will be created.

`No Access-Control-Allow-Origin' header is present on the requested resource`

**Comment by humerh** [comment]
Can you check if it is ok now??

**Comment by therter** [comment]
> Can you check if it is ok now??

It works now, thank you
