### ISSUE TITLE
EMIKAT calculation not triggered by CSIS

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/emikat#19]
Emikat id: 3179

The recalculation failed, see illustration

![image](https://user-images.githubusercontent.com/2961790/65499018-3b80e900-debd-11e9-93b8-5f4c32b4e0ff.png)

**Comment by DenoBeno** [comment]
I have triggered two calculations with just a few minutes between them when this happened, so this may be related...

**Comment by DenoBeno** [comment]
OK, the issue is a different one: the batch-jobs aren't triggered from CSIS at all and apparently hasn't been since at least September 10-th. The error message is related to some tests Heinrich did yesterday...

The studies that are triggered by CSIS should have User=CSIS in the table shown below. In reality, CSIS user doesn't appear in the logs at all (earliest log is from 10.09.2019)

![image](https://user-images.githubusercontent.com/2961790/65501650-a502f680-dec1-11e9-9cad-03655c044895.png)

So this is an issue for @patrickkaleta to see why we aren't triggering EMIKAT anymore.

**Comment by patrickkaleta** [comment]
> So this is an issue for @patrickkaleta to see why we aren't triggering EMIKAT anymore.

Emikat is triggered by CSIS as explained [here](https://github.com/clarity-h2020/emikat/issues/20#issuecomment-534513357), but then something goes very bad on Emikat side and a 500 error is returned to CSIS.

**Comment by patrickkaleta** [comment]
This was solved by @humerh. Closing it now.
