### ISSUE TITLE
No impact maps shown on https://csis.myclimateservice.eu/study/1/step/22/view/maps

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/emikat#2]
At first this map widget shows nothing, then after a VERY long wait just a few tiles appear. 

![risk-impact - map](https://user-images.githubusercontent.com/42167036/55070757-40d4b680-5087-11e9-878e-4fb9a553da13.png)

This is for the "damage level 1, event 1". The naming convention is also strange; events have names but these names either aren't used or the widget isn't even aware of them?

**Comment by p-a-s-c-a-l** [comment]
@bernhardsk Most likely a problem with EMIKAT WMS.

**Comment by patrickkaleta** [comment]
Loading the impact layers takes sometimes  up to over a minute:
![impact-map loading time](https://user-images.githubusercontent.com/42167036/55142842-d6cb1880-513d-11e9-86ea-ac707cd15930.png)

For comparison, loading the hazard layers is much faster (only around 200ms):
![hazard-map loading time](https://user-images.githubusercontent.com/42167036/55142914-f5c9aa80-513d-11e9-913a-86540a80e652.png)

@bernhardsk @humerh 
[This](https://service.emikat.at/geoserver/clarity/wms?cql_filter=HAZARD_EVENT_ID=3&service=WMS&request=GetMap&layers=clarity%3Aview.2813&styles=&format=image%2Fjpeg&transparent=true&version=1.1.1&width=256&height=256&srs=EPSG%3A3857&bbox=1589890.1883316662,4987363.221551178,1592336.173236792,4989809.206456305) is one example of how the URLs look like, that are used by the map-component to get the impact layers. Is this the right URL to get the impact layers or are there other ways on how to get that layer much faster?

**Comment by patrickkaleta** [comment]
@humerh just provided me with this [URL](https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel3Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image%2Fgif&cql_filter=HAZARD_EVENT_ID=4) to get the impact layer, which only took me around 7 seconds to load.

@therter could you please have a look at this URL (**after the review**) and checker whether it would be possible to use this format for a request to Emikat?

**Comment by therter** [comment]
This format is used. But there the map-component use tiles. So there will be several simultaneous requests. And I think that is the reason for the bad response time. But will I try to configure the map-component so that it use only one tile.

**Comment by therter** [comment]
@bernhardsk You can also add the Cache-Control response header to your WMS response to avoid the reloading from the server every time, you activate the map layer

In geoserver, you can do this by selecting the layer (click on the layer link on the left side and click then on the name of the layer)
![SelectLayer](https://user-images.githubusercontent.com/1788509/55559580-ccd18880-56ee-11e9-9051-d28571f60a54.png)

and activate the "Response Cache Headers" checkbox and set the caching time in seconds

![Layer](https://user-images.githubusercontent.com/1788509/55559591-d0fda600-56ee-11e9-965b-8a182a0d6203.png)

**Comment by bernhardsk** [comment]
Dear Thorsten, thank you for this info. Heinrich changed the setting. I tested it in CSIS. Already loaded layers now appear instantly. 

The initial loading time is now at around 7-8 seconds per newly requested layer instead of 1,5 minutes, so thank you for changing the way in which the tiles are handled.
