### ISSUE TITLE
Studies not getting the EMIKAT ID assigned

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/emikat#20]
probably related to: https://github.com/clarity-h2020/emikat/issues/6, https://github.com/clarity-h2020/emikat/issues/5

We have just noticed that new studies aren't getting the EMIKAT ID assigned anymore. This has probably been the case for a while already. Please check & fix.

**Comment by DenoBeno** [comment]
See also https://github.com/clarity-h2020/emikat/issues/19

**Comment by patrickkaleta** [comment]
The problem has to be on Emikat side, since POSTs and PUTs currently don't work even when using the Emikat Swagger interface (so without any CSIS involvement). I already informed Heinrich and he is working on it.

**BTW:** I configured the CSIS helpers module to log some status messages when Studies are being sent to Emikat. You can find those message here: https://csis.myclimateservice.eu/admin/reports/dblog?type%5B%5D=EmikatHelperFunctions&hostname=

There you can see that it last worked last week on 18.9.2019. Then, until today, there were no other attempts to send Study updates to Emikat.

**Comment by patrickkaleta** [comment]
@humerh solved the problem. Our POST and PUT requests are being processed properly again by Emikat.

**Comment by DenoBeno** [comment]
Excellent. I hope it will stay this way.

**Comment by p-a-s-c-a-l** [comment]
@humerh It still doesn't seem to work for [this study](https://csis.myclimateservice.eu/study/33/).

**Comment by patrickkaleta** [comment]
> @humerh It still doesn't seem to work for [this study](https://csis.myclimateservice.eu/study/33/).

This study doesn't yet have a data package and study area. That's why Emikat is not informed about this study and therefore there is also no emikatID available. (The csis helpers module checks for those relevant fields and informs Emikat only if they are available/have changed.)

A while ago I [discussed](https://github.com/clarity-h2020/emikat/issues/6) with @humerh what would be considered relevant information for Emikat to be able to start the calculations. That is also mentioned in the [readme.md](https://github.com/clarity-h2020/emikat/blob/master/README.md) of the Emikat repository.

I will add this information about the relevant fields in the readme of the csis helpers module as well.

**Comment by patrickkaleta** [comment]
Additionally, I can also create another Drupal log message indicating each time a request is **not** send to Emikat after a Study update. But that could spam our [log messages](https://csis.myclimateservice.eu/admin/reports/dblog), so I would only use this for a limited time.

**Comment by p-a-s-c-a-l** [comment]
Ah, ok, my fault. Now there is a study id but still no data from EMIKAT, e.g. Population Exposure: https://service.emikat.at/EmiKatTst/api/scenarios/3209/feature/tab.CLY_EL_POPULATION_INTERPOLATED.2016/table/data?rownum=1000

How long does that take @humerh ?

**Comment by DenoBeno** [comment]
In my opinion, you should show messages on the top of the page: emikat
triggered, EMIKAT not triggered because...

At least for admins and developers...

**Comment by p-a-s-c-a-l** [comment]
Although the EMIKAT ID 3209 is now assigned to [study 33](https://csis.myclimateservice.eu/study/33/) and EMIKAT ID 3189 to [study 35](https://csis.myclimateservice.eu/group/35), EMIKAT calculation [was not triggered](https://github.com/clarity-h2020/emikat/issues/10#issuecomment-535044443). But the logs show:

![grafik](https://user-images.githubusercontent.com/1788226/65609947-e32b1380-dfb0-11e9-95be-1be6d522153a.png)

![grafik](https://user-images.githubusercontent.com/1788226/65610485-b4fa0380-dfb1-11e9-8b2a-498706fe4a99.png)

**Comment by patrickkaleta** [comment]
> In my opinion, you should show messages on the top of the page: emikat triggered, EMIKAT not triggered because... At least for admins and developers...

Probably a good idea for developers and admins. I'll have a look at how to implement something like that.

**Comment by patrickkaleta** [comment]
> Although the EMIKAT ID 3209 is now assigned to [study 33](https://csis.myclimateservice.eu/study/33/) and EMIKAT ID 3189 to [study 35](https://csis.myclimateservice.eu/group/35), EMIKAT calculation [was not triggered](https://github.com/clarity-h2020/emikat/issues/10#issuecomment-535044443). But the logs show:
> 

Emikat is indeed triggered and a batch job is created and queued (Denis and I checked this via an Emikat Client), but it seems that a previous batch job got stucked. Heinrich is not in the office today, but we already called to inform him of this issue. He'll get it fixed soon hopefully.

**Comment by DenoBeno** [comment]
I think that this is fixed now. In emikat client, all teh batch jobs have been finished...

Trying to trigger the https://csis.myclimateservice.eu/study/33/ again.... Yes, it's working.

![grafik](https://user-images.githubusercontent.com/2961790/65702559-80567c80-e083-11e9-80f3-9cddce0a8cf7.png)

I'm curious to see how long it takes to run it all now...

**Comment by DenoBeno** [comment]
aproximately 6 minutes.

![grafik](https://user-images.githubusercontent.com/2961790/65703772-99f8c380-e085-11e9-9147-fda8572458a6.png)

For the future reference - if it isn't done in 10-15 minutes, then we have a problem.

**Comment by DenoBeno** [comment]
Ropening this. 

While EMIKAT does finish the calculation batch job, some data is not available for the study #33. E.g., all of these are empty:

![image](https://user-images.githubusercontent.com/2961790/65706136-19889180-e08a-11e9-8487-b218e0ccc6ab.png)

Unsurprisingly, nothing is shown on csis either.

![image](https://user-images.githubusercontent.com/2961790/65706184-30c77f00-e08a-11e9-969f-1c93432e5ad5.png)

Same for study 35. :-(

**Comment by DenoBeno** [comment]
Oh, come on. I tried to get a calculation working for linz and nothing happened. Logs say:

![image](https://user-images.githubusercontent.com/2961790/65706832-9a945880-e08b-11e9-9d20-01dd5e660c3e.png)

Nothing in EMIKAT batch-jobs.

The EMIKAT did start calculation when I changed the area again. 

![image](https://user-images.githubusercontent.com/2961790/65706961-d7f8e600-e08b-11e9-8dbe-1dea20d58d46.png)

For linz, I do get the population, but no local effect data. :-(

![image](https://user-images.githubusercontent.com/2961790/65707663-47230a00-e08d-11e9-9bf2-e9ed5679e85e.png)
![image](https://user-images.githubusercontent.com/2961790/65707855-a1bc6600-e08d-11e9-95de-8b11518821c1.png)

For the reference: "result = 0" in emikat client means that no data was generated.

![image](https://user-images.githubusercontent.com/2961790/65708055-ffe94900-e08d-11e9-9891-b3c24f64ad6f.png)

Batch took 5-6 minutes again.

**Comment by DenoBeno** [comment]
I tried for Napoli in the hope that there we would have all the data.. Result: a new type of error.

![image](https://user-images.githubusercontent.com/2961790/65708872-d4675e00-e08f-11e9-8874-cb9da49885d2.png)

Napoli, second try, with different area.. First the server reconnected....

![image](https://user-images.githubusercontent.com/2961790/65709050-36c05e80-e090-11e9-8eb9-4ffca0a3bc28.png)

Then the UA fraction and population and all other layers built as they should:

![image](https://user-images.githubusercontent.com/2961790/65709422-0dec9900-e091-11e9-83e9-824d10540a4d.png)

Which doesn't mean that they are also shown on CSIS. Hm.... OK, this time EMIKAT is producing the data as required, so we also have an issue with the CSIS app...

![image](https://user-images.githubusercontent.com/2961790/65711124-8acd4200-e094-11e9-8d1b-754018771eab.png)

**Comment by p-a-s-c-a-l** [comment]
> Which doesn't mean that they are also shown on CSIS. Hm.... OK, this time EMIKAT is producing the data as required, so we also have an issue with the CSIS app...

The table and thus EMIKAT API do not receive the variables values we have agreed upon, see https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535789402.

So probably that's an issue of the [taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_variable_meanings/overview) / paragraph / whatever? We need *value* not *meaning*. I tried to fix it in csis-helpers-module, but it [didn't work](https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535793079).

**Comment by DenoBeno** [comment]
> 
> 
> > Which doesn't mean that they are also shown on CSIS. Hm.... OK, this time EMIKAT is producing the data as required, so we also have an issue with the CSIS app...
> 
> The table and thus EMIKAT API do not receive the variables values we have agreed upon, see [clarity-h2020/csis-helpers-module#14 (comment)](https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535789402).
> 
> So probably that's an issue of the [taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_variable_meanings/overview) / paragraph / whatever? We need _value_ not _meaning_. I tried to fix it in csis-helpers-module, but it [didn't work](https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535793079).

Ah, I wasn't aware of that one. OK, this shouldn't be that difficult to fix. If nothing else works, we'll replace the paragraph with node...

**Comment by patrickkaleta** [comment]
> > Which doesn't mean that they are also shown on CSIS. Hm.... OK, this time EMIKAT is producing the data as required, so we also have an issue with the CSIS app...
> 
> The table and thus EMIKAT API do not receive the variables values we have agreed upon, see [clarity-h2020/csis-helpers-module#14 (comment)](https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535789402).
> 
> So probably that's an issue of the [taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_variable_meanings/overview) / paragraph / whatever? We need _value_ not _meaning_. I tried to fix it in csis-helpers-module, but it [didn't work](https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535793079).

The problem with the `meaning ` and `value` field should be [resolved](https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535830997) for now. 
@p-a-s-c-a-l: Can you confirm that your apps are getting correct values for `emission_scenario`, `time_period`,...?

> > ...
>
> Ah, I wasn't aware of that one. OK, this shouldn't be that difficult to fix. If nothing else works, we'll replace the paragraph with node...

@DenoBeno no, this should not be necessary. Extracting fields out of the paragraphs turned out to be quite straightforward, so IMO the current structure is fine and doesn't need to be changed again.

**Comment by patrickkaleta** [comment]
I have now also improved the status notifications as proposed by Denis. In addition to the log messages in the BE, Admins and developers now see directly in the FE, if Emikat has been triggered or not, after updating a Study (as well as whether or not a Recalculation will be evoked).

**Only exception:** changing the Study area doesn't show those notifications, since the Study is updated inside the map-component via REST and no page-reload is triggered. In those cases there will be only the log messages in the [BE](https://csis.myclimateservice.eu/admin/reports/dblog?type%5B%5D=EmikatHelperFunctions&hostname=) available.
![status messages](https://user-images.githubusercontent.com/42167036/65770748-ff58bd00-e136-11e9-8912-c67c6ed2882b.png)

**Comment by p-a-s-c-a-l** [comment]
> Can you confirm that your apps are getting correct values for `emission_scenario`, `time_period`,...?

yes, it is.

**Comment by DenoBeno** [comment]
> So probably that's an issue of the [taxonomy](https://csis.myclimateservice.eu/admin/structure/taxonomy/manage/dp_variable_meanings/overview) / paragraph / whatever? We need _value_ not _meaning_. I tried to fix it in csis-helpers-module, but it [didn't work](https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535793079).
...

As explained in https://github.com/clarity-h2020/csis-helpers-module/issues/14#issuecomment-535830997, this is not really a bug, rather a design feature that we'll need in the future. For now, you can ignore it, I have configured the "DP variable meanings" entries in such a way that they deliver the same information as "DP variables". 

That's OK as long as we *only* use the variables with EMIKAT. The moment we start implementing the variables support for other resources, there will be more than one "DP variables" entry possible for each  "DP variable meanings" entry. E.g., the "historical" time period will map to "Baseline" for EMIKAT and to "historical" for the heat hazards, see https://github.com/clarity-h2020/data-package/issues/47#issuecomment-533827669 .

**Comment by DenoBeno** [comment]
Guess we can close this issue?

**Comment by patrickkaleta** [comment]
> Guess we can close this issue?

Yes, we can close this. Emikat IDs are assigned to studies once they have all the [relevant](https://github.com/clarity-h2020/csis-helpers-module#communication-with-emikat) fields filled out.
