### ISSUE TITLE
Please test and if needed calibrate the local temperature estimates

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/emikat#24]
Related: https://github.com/clarity-h2020/local-effects/issues/8, https://github.com/clarity-h2020/emikat/issues/28, https://github.com/clarity-h2020/data-package/issues/59

I took a look at the local temperature estimates produced by EMIKAT and I'm concerned about the MRT being over 100°C. I am even more concerned about the relation between ambient, MRT and UTCI index. 

http://www.utci.org/utcineu/utcineu.php

If this calculator is any good, then the relations between the tree temperatures we are getting in Athens are suspect. These are all from the same table, notice how different a value I have to put for humidity. Do we even have the data on humidity and wind velocity?

![image](https://user-images.githubusercontent.com/2961790/66240403-d74ff780-e6fc-11e9-8f10-d774f0446e40.png)

![image](https://user-images.githubusercontent.com/2961790/66240532-33b31700-e6fd-11e9-8610-a11d781c5c69.png)

![image](https://user-images.githubusercontent.com/2961790/66240567-4d545e80-e6fd-11e9-9dda-366411a38f3e.png)

![image](https://user-images.githubusercontent.com/2961790/66240694-a1f7d980-e6fd-11e9-8dfe-c1fd6e360f18.png)

![image](https://user-images.githubusercontent.com/2961790/66240763-dec3d080-e6fd-11e9-8c36-c4a17b67ea92.png)

![image](https://user-images.githubusercontent.com/2961790/66241031-61e52680-e6fe-11e9-887b-cf4694817d83.png)

The temperature table is from https://csis.myclimateservice.eu/study/35/step/1524/view/table

**Comment by RobAndGo** [comment]
To my knowledge there has been no mention of what relative humidity or wind speeds are used in the calculation of UTCI. We have not provided any humidity data from EURO-CORDEX and wind data is only available in the form of a wind index averaged over the 30-year periods. I'm not sure if PLINIVS @stefanon or @mattia-leone can provide any further information.

**Comment by DenoBeno** [comment]
> To my knowledge there has been no mention of what relative humidity or wind speeds are used in the calculation of UTCI. We have not provided any humidity data from EURO-CORDEX and wind data is only available in the form of a wind index averaged over the 30-year periods. I'm not sure if PLINIVS @stefanon or @mattia-leone can provide any further information.

So how IS the UTCI calculated? @stefanon? @humerh? 

How do we calculate UTCI without humidity & wind speed if this are the parameters that go into UTCI calculation?

**Comment by stefanon** [comment]
Hi, all
about UTCI calculation, we implemented it only for expert level evaluation. The parameters required include the humidity and wind speed, other then Ta and Tmrt. The UTCI evaluation is done applying the Simplified Model proposed by Błażejczyk, (2011). The humidity and wind speed for expert level local scale used in calculations is retrieved from meteo data of local stations, for the day(s) of the analysis.
I checked also the linked UTCI calculator, with these results related to input parameter:
1.  Ta=36 Tmrt=(50+36) hr%=67 V=1 my result is UTMCI=54.97°C instead of calculator 52.7 
2.  Ta=38 Tmrt=(38+57) hr%=48 V=1 UTMCI=57.19 instead of 55
2.  Ta=40.5 Tmrt=(40.5+61.5) hr=38 V=1 UTMCI=61.09 instead of 58.6

**Comment by humerh** [comment]
This document (specification) was provided by PLINIVS:

[Conversion of Mean Radiant Temperature to Apparent temperature.docx](https://github.com/clarity-h2020/emikat/files/3709307/Conversion.of.Mean.Radiant.Temperature.to.Apparent.temperature.docx)


This was the document forwarded to me after the Vienna meeting in summer.

**Comment by DenoBeno** [comment]
OK, the way this is calculated is clear now:

![image](https://user-images.githubusercontent.com/2961790/66550761-5a7eac80-eb46-11e9-8e7b-c30874c0c4ed.png)

I just don't understand why this approximation is so far from what the calculator gives. My 1 m/s is quite near to 1.1m/s, so the humidity of ca. 50% should produce similar results in that calculator. Also the tests made by @RobAndGo indicate that the calculator is not so far off. Unfortunately I don't have time to do much testing tests with 1.1 m/s and 50% humidity at the moment.

this one looks OK
![image](https://user-images.githubusercontent.com/2961790/66551098-15a74580-eb47-11e9-8f55-5e2892154805.png)
![image](https://user-images.githubusercontent.com/2961790/66551213-4edfb580-eb47-11e9-9b13-5375fb36a4e6.png)

I hope it's OK.

**Comment by DenoBeno** [comment]
Maybe this isn't such a showstopper anymore, but we will still need some validation of this data against reality or against a better model.

**Comment by DenoBeno** [comment]
I talked with Wolfgang Loibl today. He will start validating this data against Linz data where we have both the measurements and the more accurate models. In his opinion, our T_MRT is far too high and therefore also the T_UTCI.  This would also explain why the comfort index based on T_UTCI is almost always 5.

**Comment by DenoBeno** [comment]
_latest e-mail from Wolfgang:_ 

Denis showed today the SCIS – application to me as I don’t have an account (until now!) …

I recognised the T-mrt results draped over Europe and was quite alarmed – **the modelled results are far away from reality compared to our high resolution simulations and the monitoring results, which we are conducting for model result validation**

The validation of  the Linz microclimate simulation results, comparing monitoring with professional weather station equipment  with simulation results of ENVIMET and Grasshopper is in progress 
The validation of  microclimate simulation for our research campus comparing infrared imaging with simulation results of ENVIMET and Grasshopper is finalised.

These discrepancies  can also confirmed by checking other papers.

Here is the link for a paper in the International Journal of Biometeorology on “Present and projected future mean radiant temperature for three European cities “ found by Milena (thanks!):

https://link.springer.com/article/10.1007%2Fs00484-017-1332-2

Below you find the MRT results for the central city patches for 3 Cities from north to south of Europe over the year  for different climate periods, carried out with SOLWEIG – delivering similar results as Grasshopper.

![image](https://user-images.githubusercontent.com/2961790/68228626-0e644200-fff6-11e9-9630-dfd79fdd05b2.png)

The average maxima during the summer months range between 45 and 55 °C 
Our T-mrt  values for Linz and Vienna at peak temperature days show maxima of around 70°C, and reach during summer frequently around 50”C like shown in the article 

The SCIS MRT-scale is reaching 100 to 120°C !
I checked – this cannot be possible! 
Pls revise the parameterisation ….

**Comment by stefanon** [comment]
We are working on DC1 detail scale and validating results for Tmrt and the dependent UTCI, evaluating also model sensitivity to the parameters used and attributed to the landuse layers, and as we have also available the data at feasebility level, we'd like to compare calculation results done with our procedure with the ones done in Emikat: can I have a look at the procedure doing calcs (should it be some Postgres code?) and access to the results in the database?

**Comment by DenoBeno** [comment]
sure. You need to talk with @humerh about this. I noticed him sending some data per e-mail to Tanja the other day, maybe that's exactly what you need. 
As for accessing the DB, we have an EMIKAT client application that can be used for this purpose. You would need a special login/password and a bit of training to use it though.

**Comment by DenoBeno** [comment]
Just FYI, I found some data sets. Ist this useful?

•	https://doi.pangaea.de/10.1594/PANGAEA.879722

A database containing irradiances of ultraviolet and visible components of the surface solar 10-minute irradiation measured from July 2014 to December 2016 at three stations in the area of the city of Ostrava (Czech Republic) is presented. The measured variables contain irradiances of UVB (280-315 nm), UVA (315-380 nm), intervals of 400-700 nm (photosynthetically active radiation, PAR), 510-700 nm, 600-700 nm, 610-680 nm (called 660 nm), 690-780 nm (called 730 nm), and global radiation (400-1100 nm). In addition, a series of meteorological variables including relative air humidity and air temperature is provided at the same 10-minute resolution at all stations. For two stations there are additional data: PM10, SO2, NOx, NO, NO2 concentrations, air temperature and relative humidity, air pressure, wind speed and wind direction. The details of the experimental sites and instruments used for the measurements are given. Special attention is given to the data quality while the process applied to label suspicious or erroneous measurements is described in detail. Between 93 and 99% of the measured values which were higher than threshold values for each spectral region of incident solar radiation are validated by this quality check. About 130 000 records for the all three stations are available in the database. Due to high temporal resolution of data, this database is a reliable source for estimation of radiation environment in highly polluted areas of industrial cities in the middle of Europe.

More data (available for various years)

•	Sonnblick: https://doi.pangaea.de/10.1594/PANGAEA.900670 
•	Palleisau, France: https://doi.pangaea.de/10.1594/PANGAEA.899709
•	Payerne, Swizerland: https://doi.pangaea.de/10.1594/PANGAEA.898017
•	Izana, Tenerife, spain: https://doi.pangaea.de/10.1594/PANGAEA.907129
•	Cabauw, Nl: https://doi.pangaea.de/10.1594/PANGAEA.905898

**Comment by RobAndGo** [comment]
Just returning to the comment that @DenoBeno made [above](https://github.com/clarity-h2020/emikat/issues/24#issuecomment-540456558). I think the difference between the value of UTCI from Emikat and that from the online calculator (http://www.utci.org/utcineu/utcineu.php) is because the equation that Emikat uses, namely this one: 

![image](https://user-images.githubusercontent.com/45385637/70805185-a228eb00-1db8-11ea-87e1-98d28391e03c.png)

is only an **approximation** to the actual expression for UTCI. In the paper by Blazejczyk et al. 2013 "_An Introduction to the Universal Thermal Climate Index_" the UTCI is expressed in general terms as:

![image](https://user-images.githubusercontent.com/45385637/70805281-d56b7a00-1db8-11ea-806d-433eb3faf682.png)

Here the offsets of UTCI are "_approximated by a polynomial in Ta, va, vp, Tmrt-Ta including all
the main effect and interaction terms up to the 6th order. The least-squares estimates of the 210 co-
efficients were found (Błażejczyk et al. 2010; Błażejczyk & Kunert 2011)._" That is, the online calculator uses this more precise expression. The fortran program that the calculator is based upon can be found [here](http://www.utci.org/utci_doku.php) in the subdirectory "UTCI Program Code".

If we want a more precise value of UTCI, perhaps this code can be transferred into Emikat?

Furthermore, the equation of UTCI that we use comes from the Blazejczyk (2011) article "_Mapping of UTCI in local scale (the case of Warsaw)_", and they refer to the UTCI calculated from this equation as UTCI* to indicate that it is a simplified equation of UTCI.

**Comment by p-a-s-c-a-l** [comment]
Has this been addressed? Are we confident with the calculated results? Can this be offered as public service now?

**Comment by DenoBeno** [comment]
Mattia says that the temperature ranges are as they should now. Validating the results against better models is still on TODO

**Comment by p-a-s-c-a-l** [comment]
Great! So we can close. Validation is discussed [here](https://github.com/clarity-h2020/emikat/issues/35)
