### ISSUE TITLE
Calculation for mortality rates - documentation and open problems with EUROSTAT- Database

### ISSUE THREAD

**Issue by humerh** [clarity-h2020/emikat#26]
The implementation starts with the definition by PLINIVUS "impact.calculation_mortality_v3.docx":

In the chapter 3 the "Calculation of deaths" is described:
![image](https://user-images.githubusercontent.com/20284964/66380919-9e43ab80-e9b8-11e9-9009-8159367e4ea3.png)

It is suggest to use the statistic database from EUROSTAT: https://ec.europa.eu/eurostat/web/cities/data/database 

The year 2012 (same year of Copernicus population dataset) was suggested.

For our purpose two datasources are required:
  Database urb_cfermor, containing 
    - Fertility and mortality for cities and greater cities  (index-Code: SA2019V - Total deaths per year)
  Database urb_cpop, containing
    - Population statistics (index-Code: DE1001V - Population total)

Both databases are defined for "urban areas" in Europe.
The definition of urban areas confirming https://ec.europa.eu/eurostat/documents/4313761/4311719/Metro_reg_Defining_urban_areas is used in the database.

It is necessary to use the same boundings of city areas for both statistic sources for all cities in Europe.

The (filtered) imput files from Eurostat are atteched:

[mortality_tables.zip](https://github.com/clarity-h2020/emikat/files/3701581/mortality_tables.zip)

**Comment by humerh** [comment]
I implemented a database for these data in EMIKAT and imported the values for the suggested yeaar 2012.

The result is like this:
![image](https://user-images.githubusercontent.com/20284964/66384134-79523700-e9be-11e9-898f-a83c052ccfbf.png)


The columns "Total deaths per year" and "Total population" come from different sources but they use the same Urban area code UA_CODE_2017. I joined them in one table.

**Comment by humerh** [comment]
There are some open problems about this database:

- For the selected Year 2012 not all urban areas contain information, they are empty or they are flagged.
- As consequence the impact calculation can not generate results.

What are possible workarounds:

- Find another data source
- Use the values of another year
- Adding missing values manually (expert estimation)
- replacing missing values by an European average mortality rate

PLINIUS @mattia-leone , please help me to find a practical solution

**Comment by DenoBeno** [comment]
As we agreed today, the procedure is the following:

1. Make it work where the data is available
2. make sure some kind of error is issued where this is not possible
3. Then try to implement some workaround, e.g. take values for some nearby region or EU-average or...
4. indicate if the data was calculated in this way.
5. Finally, @helllth will then have to show this information to the users.

**Comment by p-a-s-c-a-l** [comment]
Workaround is documented [here](https://github.com/clarity-h2020/emikat/issues/25#issuecomment-542082667).
