### ISSUE TITLE
Study in Poland doesn't show any results for local HC and RIA

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/emikat#29]
- [ ]  ~adding new study doesn't generate all the necessary table entries (always?)~
- [ ] ~impact calculation fails in many places, e.g. Lodz, Gdansk and Tirana regions. It works in Vienna, Linz, Barcelona, Athens, Naples...~
- [ ] ~In Lodz region, no temperature and population results were shown on a map.~

**See my updates in [this comment](https://github.com/clarity-h2020/emikat/issues/29#issuecomment-555931959).**

---------------------
Study 25 (emikat ID: 3183) was just calculated and finished roughly after 15 minutes (with no apparent erros), however the layers for HC local effects and for Risk and Impact assessment don't show anything. (here one [example](https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3183&&service=WMS&request=GetMap&layers=clarity%3Aview.2974&styles=T_UTCI%0D%0A&format=image%2Fpng&transparent=true&version=1.1.1&leaflet=%5Bobject%20Object%5D&width=1536&height=1536&srs=EPSG%3A3857&tileSize=1536&attribution=&bbox=1800244.8901724715,6829189.85511079,1858948.527895487,6887893.492833805) of a result layer for RIA).

BatchJobs look all ok, so I don't know where exactly to look for the error. @humerh can you please investigate this further? Maybe just some kind of caching problem and the result layers are actually already there and showing something?

**Comment by DenoBeno** [comment]
"Projects for adaptation" table is empty. In other studies, there is one line for it in the table:

![image](https://user-images.githubusercontent.com/2961790/68298314-525c5300-0099-11ea-9840-213e2b3b5d60.png)

Could it be that this entry isn't getting made in new studies anymore? I usually experiment with old studies but this one is new.

**Comment by DenoBeno** [comment]
If I do the calculation in Poland by re-using some old study, most of the views are built correctly but the mortality isn't:
![image](https://user-images.githubusercontent.com/2961790/68310287-08329c00-00b0-11ea-8913-67a8389b4bf8.png)

**Comment by DenoBeno** [comment]
More test results:

I tried to perform a study on several places yesterday. Two in Poland and Tirana/Albania. Always starting from existing study because starting a new study apparently doesn't work properly (see earlier message).

1. Small village near Gdansk
- everything worked except for calculating the impact.
2. Lodz area: city centre and a village next to it.
- calculations apparently worked, but I wasn't able to see anything in CSIS.
3. Tirana
- everything worked except for the impact calculation.

So there are at least two things broken that can be easily repeated:
1. adding new study doesn't generate all the necessary table entries (always?)
2. impact calculation fails in many places. It did work in Barcelona...

![image](https://user-images.githubusercontent.com/2961790/68376523-023cc980-0149-11ea-8279-62580b5b8c36.png)

The third one is more difficult. Why would the system calculate everything correctly but fail to show it? in Lodz region? I tried it 3 times there before moving to Tirana - 3x failed and Tirana worked immediately.

**Comment by humerh** [comment]
One part of the problem:
In the study definition the city is called LODZ.
In the city table for mortality rates the city PL002C1 is called "Łódź"
Similar, but not the same writing.
For comparing we should switch to city codes.

**Comment by DenoBeno** [comment]
Yes, I can imagine this could cause problems...

**Comment by patrickkaleta** [comment]
> One part of the problem:
> In the study definition the city is called LODZ.
> In the city table for mortality rates the city PL002C1 is called "Łódź"
> Similar, but not the same writing.
> For comparing we should switch to city codes.

We are currently not storing city codes in Drupal, but I don't think it should be much of a problem to add them to our City/Region taxonomy. Once we have those city codes, I could update the CSIS helpers module to send the city code as well everytime we trigger Emikat.

**Comment by DenoBeno** [comment]
Sure. One field more....

**Comment by patrickkaleta** [comment]
### Update:
After looking deeper into those problems together with @humerh we found and solved/are working on solving the following problems:
- for new Studies no calculations were triggered, because Emikat was expecting the `forceRecalculate` attribute, which CSIS only sends when updates in existing Studies occur. Heinrich fixed this on Emikat-side and once a new version of Emikat will be deployed that error should disappear
- for some of the existing studies the calculations showed no result due to a missing entry in one of the tabels (@DenoBeno noticed that in his [comment](https://github.com/clarity-h2020/emikat/issues/29#issuecomment-550332175)). That was caused by a problem with the versioning, which should be fixed now
- another reason for no results is a [mismatch between the city names](https://github.com/clarity-h2020/emikat/issues/29#issuecomment-553431127), therefore we are currently switching to unique study codes (ongoing in this [issue](https://github.com/clarity-h2020/docker-drupal/issues/128))
