### ISSUE TITLE
Replace automated study triggering with a dedicated "(re)calculate" button

### ISSUE THREAD

**Issue by DenoBeno** [clarity-h2020/emikat#34]
As it is, it's too easy to hit the re-calculation while the old calculation is already running. This has various negative effects. In the best case, it uses the resources unnecessary and makes the user wait longer than needed. Basically, if two calculations are triggered in the short time, user wil lend up looking at "0 from 11 processes" message for some 15 min or longer. In the worst case, user could try again and again and block EMIKAT for hours. We may choose to ignore this, but I'll mark it as SHOWSTOPPER for now.

Before letting some external (impatient) users to trigger study calculations, we IMO need to somehow handle this issue. I can see two possibilities:

- either make it possible to stop already running calculation before starting a new one
- or make it impossible for the user to start new calculation while the old one is running.

After a discussion with @humerh , it would seem that the first option is difficult to implement. So the question is "can we go for the second one?". What I have in mind is to:

1. Replace the automatic triggering of the calculation by explicit triggering by the user (press the "calculate" button).
2. Disable this button if a calculation is already running, as well as in the case not all parameters are set.

Necessary logic:

- is the study of the correct type?
- is area defined?
- is the EMIKAT "free"? (no calculation for this study currently running)

If all three are true, the (big, friendly, green) "re-calculate" button is shown to the user/can be clicked. If not, it's not shown or disabled (e.g. red or grey).

WDYT?

**Comment by p-a-s-c-a-l** [comment]
- KISS Solution: Don't allow re-calculation at all. If somebody wants to define  new study area, she/he has to create a new study.
- True agile approach: Implement the KISS solution, make [beta release](https://github.com/clarity-h2020/csis/issues/145), implement support for re-calculations, make next release

**Comment by patrickkaleta** [comment]
After discussions with Denis and seeing [usability](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-597617917) and [stability](https://github.com/clarity-h2020/docker-drupal/issues/141#issuecomment-597078027) issues, **the automated Emikat trigger has now been disabled and replaced** by a "Start calculations" button, which can be triggered by the Study owner in the Study summary tab.

This button (~a [Display Suite token field](https://csis.myclimateservice.eu/admin/structure/ds/fields/manage_token/trigger_calculation)~ **UPDATE: Button now created directly in the View-block of the Sidebar**) is visible only to Study owners in Studies, that require a calculation in Emikat (ATM just "Advanced Screening: Urban Infrastructure") and only functional if necessary fields are set and no calculation is currently running for this study.

In addition, I've added a [Study checklist block](https://csis.myclimateservice.eu/admin/structure/views/view/study_group_overview/edit/block_3) into the right sidebar, that gives some information about what's required for the calculations and whether or not is has already been configured. This block is only visible to members of Studies, that require Emikat for calculations.

Visibility of both, the Trigger-button and the Checklist block, as well as the logic behind the trigger mechanism are handled by the [CSIS helpers module ](https://github.com/clarity-h2020/csis-helpers-module).

**Note: Emikat is not affected by any of the mentioned changes, so no action from @humerh needed.**

![trigger-emikat-button](https://user-images.githubusercontent.com/42167036/76543722-345b9080-6487-11ea-8733-bc7273ff5fd6.png)

**Comment by patrickkaleta** [comment]
> * KISS Solution: Don't allow re-calculation at all. If somebody wants to define  new study area, she/he has to create a new study.

Yes, that would've been an easier solution, but it would also give us just one shot for each study to get it right. If e.g. Emikat would suddenly generate errors (for example by [messing up the order of batch jobs](https://github.com/clarity-h2020/emikat/issues/33?email_token=AKBWV7FNOLPAI7P4KNJOVL3RG5CNLA5CNFSM4KVE3DO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOOSH4I#issuecomment-597500913)), we would get no results for those studies and have no chance to try again at some later point.

**Comment by patrickkaleta** [comment]
No complaints so far, therefore closing this issue now.

**Comment by patrickkaleta** [comment]
As proposed by @DenoBeno the trigger button is now placed inside the new sidebar instead of the Summary page of the Study.
