### ISSUE TITLE
Urban Area and Country missing in HC API request

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#40]
HC Table for Study 33 and 35 is missing Urban Area and Country: https://csis.myclimateservice.eu/study/33/step/1519/view/table 

![grafik](https://user-images.githubusercontent.com/1788226/83233398-eb1a0380-a18e-11ea-8835-fc7490ae6086.png)

The related API request: https://service.emikat.at/EmiKatTst/api/scenarios/3209/feature/tab.CLY_HAZARD_EVENTS_STUDY.2036/table/data?rownum=1000

I've recalculated study 33 but this did not resolve this issue as well as the [WMS issue](https://github.com/clarity-h2020/emikat/issues/39). FYI, in Study 1, HC table correctly shows  Area and Country: https://csis.myclimateservice.eu/study/1/step/2/view/table

So where is this information regarding Area and Country taken from? From CSIS? 

@therter  Can you please check if there's any difference between study 33 and 1 regarding the chosen country and region that may cause the Area and Country information to be missing the the Study 33 HC Table?

**Comment by therter** [comment]
> @therter Can you please check if there's any difference between study 33 and 1 regarding the chosen country and region that may cause the Area and Country information to be missing the the Study 33 HC Table?

The country and the city are correctly selected in study 33, study 35 and study 1. But perhaps, the city name or city code (I don't know, what value is used in emikat) are not identical in csis and emikat and for this reason, the city is not recognised in emikat.

The city name of study 33 is ALBA_IULIA and the city code is RO014.
The city name of study 35 is ATHINA and the city code is EL001.

**Comment by p-a-s-c-a-l** [comment]
Same problem with [this new study](https://csis.myclimateservice.eu/study/155/step/4449/view/table) in Palermo:

![grafik](https://user-images.githubusercontent.com/1788226/83873980-15426700-a735-11ea-86dc-f3f24fd2ca17.png)

Any chance that this can get fixed before the 1st webinar?

**Comment by p-a-s-c-a-l** [comment]
I've hidden the respective columns in the table - kind of a solution.
