### ISSUE TITLE
EMIKAT REST API Service Monitoring blocked?

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#43]
EMIKAT API checks that are performed by https://health-check.clarity.cismet.de now  [keep failing](https://github.com/clarity-h2020/csis-technical-validation/issues/48), although EMIKAT APIs are reachable via Browser or URL.

E.g. requests to `https://service.emikat.at/EmiKatTst/api/service/version` sent from browser or curl with appropriate basic auth headers return

> EmiKat Server [2.03-SNAPSHOT] (build 1.420 - 2020-05-26 09:13:02)  {jdbc:oracle:thin:@192.168.77.57:1532:oemikat2}

The same request sent from health-check.clarity.cismet.de suddenly stopped working and now fails with
> HTTP Status Code 400 

Perhaps there was a change on EMIKAT side to block certain domains or clients from making requests? I've double checked the configuration and also tested basic auth against https://ckan.myclimateservice.eu/. The monitoring service at health-check.clarity.cismet.de can sucessfully check service.emikat.at/geoserver but not service.emikat.at/EmiKatTst/api

**Comment by p-a-s-c-a-l** [comment]
BTW, https://service.emikat.at/EmiKatTst/swagger/index.html can be [successfully checked](https://service.emikat.at/EmiKatTst/swagger/index.html) by monitoring service, also with basic auth. 

But all requests to EmiKatTst/api keep failing with error code 400.

**Comment by humerh** [comment]
Maybe you have to use the request:
https://service.emikat.at/EmiKatTst/api/swagger.json

**Comment by p-a-s-c-a-l** [comment]
thanks!
