### ISSUE TITLE
Integration of pluvial flood model results in CSIS

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#44]
Now that [pluvial flood model in EMIKAT](https://github.com/clarity-h2020/emikat/issues/36) is implemented, I want to raise the question how to integrate the results in [Advanced Screening: Urban Infrastructure](https://csis-dev.myclimateservice.eu/taxonomy/study-type/screening-urban) studies.

1st we need to know how the PV results can be accessed. ATM, we load HW Events, HW LE (tmrt, etc.), HW Impact and HW Impact Maps from the EMIKAT APIs defined [here](https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)#emikat-apis). Are there different 'views' for HW and PV, or can we show both in **one table**? With two separate 'views' we may need also two separate tables which requires quite some changes either in table component or on Drupal Side. 

@humerh Could you please update the [list of EMIKAT APIS](https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)#emikat-apis) and iclude the 'PV views' (if any)?

Furthermore, the [European Data Package](https://csis-dev.myclimateservice.eu/node/682) has to be updated with the new EMIKAT PV resources. E.g. PV resources analogues to the [Heat mortality risk/impact screening](https://csis-dev.myclimateservice.eu/node/1356) have to be defined or existing resources have to be updated accordingly.

**Comment by humerh** [comment]
Now I have finished the implementation of Pluvial flood in version 1.0.
It includes the local effects, the impact calculation, the preparation for adaptation options and the costs.

See: 
https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)

**Comment by p-a-s-c-a-l** [comment]
See https://github.com/clarity-h2020/data-package/issues/77 and https://github.com/clarity-h2020/data-package/issues/54
