### ISSUE TITLE
Combined Heat and Flood Views

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#46]
As decided today, we want to use [one table](https://github.com/clarity-h2020/simple-table-component/issues/18) for 
- [x] Heat and Flood Exposure
- [x] Heat and Flood Hazard ❔ 
- [x] Heat and Flood Hazard with Local Effects 
- [x] Heat and Flood Impact 

and show indicators for 

- [x] **aggregated** heat and flood impact 

in [Scenario Analysis](https://github.com/clarity-h2020/scenario-analysis/issues/24). 

The respective views have to be created in EMIKAT and the list of [Service Endpoints](https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)) has to be updated.

**Comment by humerh** [comment]
Heat and Flood Exposure   -> view.2955
 Heat and Flood Hazard with Local Effects  -> view.3154
 Heat and Flood Impact  -> view.3155
 Aggregated heat and flood impact   -> view.2994

Please test the new views.

**Comment by p-a-s-c-a-l** [comment]
> Heat and Flood Exposure -> view.2955

This table does not contain any flood exposure data but just population.

**Comment by p-a-s-c-a-l** [comment]
BTW, is there no flood **hazards** data available @humerh ?

**Comment by humerh** [comment]
Heat and Flood Exposure -> view.2955
includes now also three columns from Urban Atlas for the areas
 ROADS_M2
 RESIDENTIAL_BUILDINGS_M2
 NON_RESIDENTIAL_BUILDINGS_M2

**Comment by humerh** [comment]
> BTW, is there no flood **hazards** data available @humerh ?

I don't understand. Which Study do you use?

**Comment by p-a-s-c-a-l** [comment]
> I don't understand. Which Study do you use?

Sorry, I forgot that `tab.CLY_HAZARD_EVENTS_STUDY.2036` is already a combined flood **and** heat hazards table.

**Comment by p-a-s-c-a-l** [comment]
Done. Integrated in [Tables](https://github.com/clarity-h2020/simple-table-component/issues/18#issuecomment-666354471) and [Scenario Analysis](https://github.com/clarity-h2020/scenario-analysis/issues/24#issuecomment-668445190).
