### ISSUE TITLE
EMIKAT GeoServer runs out of memory

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#48]
I've successfully tested the HC-LE PF layer:

https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3183&&service=WMS&request=GetMap&version=1.1.1&layers=clarity%3Aview.3154&styles=PF_PROP&format=image%2Fpng&transparent=true&tileSize=1536&info_format=application%2Fjson&width=608&height=496&srs=EPSG%3A3857&bbox=1801773.630738175%2C6135218.075309671%2C1825010.4873368687%2C6154174.458324397

But when I activate a 2nd layer, e.g. HC-LE HW_T_A, EMIKAT GeoServer runs out of memory:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ServiceExceptionReport  SYSTEM "https://service.emikat.at/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> 
<ServiceExceptionReport version="1.1.1" >   <ServiceException>
      java.lang.OutOfMemoryError: GC overhead limit exceeded
GC overhead limit exceeded
</ServiceException>
</ServiceExceptionReport>
```

You can reproduce with: https://csis-dev.myclimateservice.eu/study/25/step/5107/view/maps

**Comment by humerh** [comment]
Hier scheint die "bbox" nicht zu stimmen:

Euer Beispiel:
https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.3154&bbox=4672000.0,1979500.0,4687500.0,1988000.0&width=768&height=421&srs=EPSG:3035&format=image/gif&CQL_FILTER=STUDY_VARIANT='BASELINE' and TIME_PERIOD='Baseline' AND EMISSIONS_SCENARIO='Baseline' AND EVENT_FREQUENCY='Rare' AND SZ_ID=3183&styles=PF_PROP

&bbox=4672000.0,1979500.0,4687500.0,1988000.0   ist nicht in der Study-Area.

**Comment by humerh** [comment]
"out of memory" habe ich nicht rekonstruiren können.
