### ISSUE TITLE
Missing WMS Layers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#49]
[\[Impact results combined\] for each Scenario, Time period, typical Events and for each Adaptation Project:](https://github.com/clarity-h2020/csis/wiki/Services-endpoints-(used-by-CSIS)#impact-results-combined-for-each-scenario-time-period-typical-events-and-for-each-adaptation-project)

**HW_DAMAGEQUANITITY** (number of affected persons) not working:

https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3183&&service=WMS&request=GetMap&version=1.1.1&layers=clarity%3Aview.3155&styles=HW_DAMAGEQUANITITY%0D%0A&format=image%2Fpng&transparent=true&tileSize=1536&info_format=application%2Fjson&width=960&height=446&srs=EPSG%3A3857&bbox=1819048.399130625%2C6144357.077504019%2C1823634.6208277354%2C6146487.75966747

```xml
<ServiceException code="StyleNotDefined">
      No such style: HW_DAMAGEQUANITITY
</ServiceException></ServiceExceptionReport>
```

**Comment by p-a-s-c-a-l** [comment]
**HW_DAMAGEPROBABILITY** not working: 

https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3183&&service=WMS&request=GetMap&version=1.1.1&layers=clarity%3Aview.3155&styles=HW_DAMAGEPROBABILITY%0D%0A&format=image%2Fpng&transparent=true&tileSize=1536&info_format=application%2Fjson&width=960&height=446&srs=EPSG%3A3857&bbox=1819206.050501463%2C6144352.300189752%2C1823792.2721985737%2C6146482.9823532

```xml
<ServiceException code="StyleNotDefined">
      No such style: HW_DAMAGEQUANITITY
</ServiceException></ServiceExceptionReport>
```

Test with [Map Component](https://csis-dev.myclimateservice.eu/apps/map-component/build/SynchronisedRiskAndImpactMap/?host=https://csis-dev.myclimateservice.eu&study_uuid=9359e741-df40-4bcd-9faf-2093b499c65c&study_area=POLYGON%20((16.346111%2048.223997,%2016.346111%2048.238634,%2016.376667%2048.238634,%2016.376667%2048.223997,%2016.346111%2048.223997))&emikat_id=3183&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&write_permissions=1&time_period=Baseline&emissions_scenario=Baseline&event_frequency=Rare&grouping_tag=taxonomy_term--hazards) for [Study 25](https://csis-dev.myclimateservice.eu/study/25/view/intro).

Related Data Package Resource: [Heat mortality risk/impact screening](https://csis-dev.myclimateservice.eu/node/1356)

**Comment by p-a-s-c-a-l** [comment]
**PF_DAMAGEPROPABILITY** not working : 

https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%27Baseline%27%20AND%20EMISSIONS_SCENARIO=%27Baseline%27%20AND%20EVENT_FREQUENCY=%27Rare%27%20AND%20SZ_ID=3183&&service=WMS&request=GetMap&version=1.1.1&layers=clarity%3Aview.3155&styles=HW_DAMAGEPROBABILITY%0D%0A&format=image%2Fpng&transparent=true&tileSize=1536&info_format=application%2Fjson&width=960&height=446&srs=EPSG%3A3857&bbox=1819206.050501463%2C6144352.300189752%2C1823792.2721985737%2C6146482.9823532

```xml
<ServiceException code="StyleNotDefined">
      No such style: HW_DAMAGEQUANITITY
</ServiceException></ServiceExceptionReport>
```

Test with [Map Component](https://csis-dev.myclimateservice.eu/apps/map-component/build/SynchronisedRiskAndImpactMap/?host=https://csis-dev.myclimateservice.eu&study_uuid=9359e741-df40-4bcd-9faf-2093b499c65c&study_area=POLYGON%20((16.346111%2048.223997,%2016.346111%2048.238634,%2016.376667%2048.238634,%2016.376667%2048.223997,%2016.346111%2048.223997))&emikat_id=3183&datapackage_uuid=2434ce93-93d4-4ca2-8618-a2de768d3f16&write_permissions=1&time_period=Baseline&emissions_scenario=Baseline&event_frequency=Rare&grouping_tag=taxonomy_term--hazards) for [Study 25](https://csis-dev.myclimateservice.eu/study/25/view/intro).

Related Data Package Resource: [Pluvial Flood risk/impact screening](https://csis-dev.myclimateservice.eu/node/5167)

**Comment by humerh** [comment]
Schreibweise ist:
HW_DAMAGEQUANTITY (statt HW_DAMAGEQUANITITY)
Das sollte der Fehler sein.

Ich schaue gleich im Wiki nach, ob mich verschrieben habe.

**Comment by p-a-s-c-a-l** [comment]
> HW_DAMAGEQUANTITY (statt HW_DAMAGEQUANITITY)

OK. Thanks.

Open issues: no styles PF_DAMAGEPROPABILITY and HW_DAMAGEPROBABILITY in view 3155

- The requested Style can not be used with this layer.  The style specifies an attribute of PF_DAMAGEPROPABILITY and the layer is: clarity:view.3155
- No such style: HW_DAMAGEPROBABILITY

**Comment by humerh** [comment]
The correct spelling is:
HW_DAMAGEPROBABILITY
PF_DAMAGEPROBABILITY

sorry for these spelling errors.

**Comment by p-a-s-c-a-l** [comment]
Thanks. HW_DAMAGEPROBABILITY is working now but PF_DAMAGEPROBABILITY not:


```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ServiceExceptionReport 
SYSTEM "https://service.emikat.at/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> 
<ServiceExceptionReport version="1.1.1" >   <
ServiceException code="StyleNotDefined">
      No such style: PF_DAMAGEPROBABILITY
</ServiceException>
</ServiceExceptionReport>
```

- [Map](https://csis.myclimateservice.eu/study/195/step/5695/view/maps)
- [WMS Request](https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720410101-20701231%27%20AND%20EMISSIONS_SCENARIO=%27rcp45%27%20AND%20EVENT_FREQUENCY=%27Frequent%27%20AND%20SZ_ID=3566&&service=WMS&request=GetMap&version=1.1.1&layers=clarity%3Aview.3155&styles=%20PF_DAMAGEPROBABILITY&format=image%2Fpng&transparent=true&tileSize=1536&info_format=application%2Fjson&width=608&height=496&srs=EPSG%3A3857&bbox=1573532.6642786385%2C4979108.022496384%2C1596769.5208773322%2C4998064.405511106)

**Comment by p-a-s-c-a-l** [comment]
> The layers "heat damage probability" and "flood damage probability" I think can be removed, since they are not useful to end users 

See https://github.com/clarity-h2020/csis/issues/154#issuecomment-669331990

So no further action regarding PF_DAMAGEPROBABILITY required.
