### ISSUE TITLE
Improve colour scaling of layers

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#54]
>  please change the color coding of population. Green is completely misleading.  If possible, put higher density above lower density in the legend. Color coding for population should IMO be similar to color coding used by Urban atalas for urban permeation and similar. red/brown, not green. I see that Mattia has some tresholds for population too. Maybe you can use these tresholds also for color coding the map. 
*(via @DenoBeno)*

_Originally posted by @p-a-s-c-a-l in https://github.com/clarity-h2020/data-package/issues/73#issuecomment-654088923_

**Comment by p-a-s-c-a-l** [comment]
In addition, it seems that the style for [HW_DISCOMFORT_LEVEL](https://github.com/clarity-h2020/emikat/issues/53#issuecomment-670532796) needs to be adjusted. See https://github.com/clarity-h2020/csis/issues/154#issuecomment-670526066.

**Comment by humerh** [comment]
Population so OK?
![image](https://user-images.githubusercontent.com/20284964/89706659-1deb2f80-d968-11ea-8d1e-bc7f19101798.png)

**Comment by DenoBeno** [comment]
Definitely better that green.  Need to see how it look on a map.

**Comment by humerh** [comment]
> In addition, it seems that the style for [HW_DISCOMFORT_LEVEL](https://github.com/clarity-h2020/emikat/issues/53#issuecomment-670532796) needs to be adjusted. See [clarity-h2020/csis#154 (comment)](https://github.com/clarity-h2020/csis/issues/154#issuecomment-670526066).

I found an error.
Is it now ok?

**Comment by DenoBeno** [comment]
I look online and found that there are three layers showing population now.
Red one look better IMO, but it's good to have a choice.

I think that we can lave it at that now.

**Comment by DenoBeno** [comment]
Here they are
![Screenshot_20200808-115154](https://user-images.githubusercontent.com/2961790/89707616-2b0c1c80-d970-11ea-94cd-b46bb64dd4e6.png)

![Screenshot_20200808-114949](https://user-images.githubusercontent.com/2961790/89707619-32332a80-d970-11ea-9582-221ebe71add6.png)

**Comment by DenoBeno** [comment]
I looked at discomfort levels map in Linz again,  looks correct now. 
https://csis-dev.myclimateservice.eu/study/37/step/1643/view/maps

For historical /yearly events, it's quite colorful now.

**Comment by DenoBeno** [comment]
By the way,  I believe that using the north European scales in Vienna and Linz is misleading.  Especially Vienna has warm continental summers.
