### ISSUE TITLE
Configuring initial Study trigger

### ISSUE THREAD

**Issue by patrickkaleta** [clarity-h2020/emikat#6]
The [csis_helpers module](https://github.com/clarity-h2020/csis-helpers-module) now includes a new feature, which notifies Emikat of a new study (via REST call all relevant fields are sent over), once this study contains all relevant information required by Emikat. Emikat is also notified in the same way once one of those relevant fields is updated.
Currently the following fields are being considered relevant for Emikat:
- Used data package
- Country code & City
- Study area
- Study title & goal

CSIS receives and stores the Emikat-internal ID in the field `Emikat ID` in the Study group.

### Open questions:
- Does this initial transfer of Study data automatically trigger the calculations in Emikat or should that happen separately?
- Title and goal are just needed for a better overview inside Emikat, changes here shouldn't trigger a recalculation. Make use of Emikat's `status` field to indicate whether a recalculation is necessary or not?

**Comment by p-a-s-c-a-l** [comment]
We should add selected RCP and selected Time Period. See https://github.com/clarity-h2020/docker-drupal/issues/58

**Comment by DenoBeno** [comment]
See https://github.com/clarity-h2020/docker-drupal/issues/83. It would seem that this feature is broken at the moment.

**Comment by p-a-s-c-a-l** [comment]
initial  trigger is working.
