### ISSUE TITLE
Implement new Vulnerability Functions

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#7]
Once [avilable](https://github.com/clarity-h2020/emikat/issues/3#issuecomment-505320966), implement new vulnerability functions to resolve https://github.com/clarity-h2020/emikat/issues/3

**Comment by humerh** [comment]
The new Impact model is now implemented:

As WMS-Layers:

https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aview.2975&bbox=4672000.0%2C1979500.0%2C4687500.0%2C1988000.0&width=768&height=421&srs=EPSG%3A3035&format=image%2Fgif&CQL_FILTER=PROJECT_REF=1%20and%20PERIOD=%27Baseline%27%20AND%20RCP=%27Baseline%27%20AND%20FREQUENCE=%27Rare%27%20AND%20SZ_ID=2846&styles=DAMAGEQUANTITY

In this link you can adapt the follwing parameters:

PROJECT_REF=1 ... (for future selection of an alternate ADAPTATION variants)
PERIOD='Baseline' ... (Alternatives are: '20110101-20401231', '20410101-20701231' and '20710101-21001231')
RCP='Baseline' ... (Alternatives are: 'rcp26', 'rcp45' and 'rcp85')
FREQUENCE='Rare' ... (Alternatives are: 'Occassional' or 'Frequent')


SZ_ID=2846 has to be set to the current $emikatID


The color schemas (STYLE colors) are currently fixed but not optimized !!!!


As JSON:
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/data?rownum=10000&filter=PROJECT_REF%3D1&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846

As CSV:
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/csv?rownum=10000&filter=PROJECT_REF%3D1&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846

or as GeoJSON
https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/geojson?rownum=10000&filter=PROJECT_REF%3D1&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846

**Comment by p-a-s-c-a-l** [comment]
done
