### ISSUE TITLE
Support for Adaptation Scenarios [IAO/AAO API]

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#8]
Provide an API to create new Adaptation Scenarios by modifying and land use distribution as well the parameters like albedo.

**Comment by p-a-s-c-a-l** [comment]
> Now, I have implemented the calculation of adptation option in a way, that either the land use distribution as well the parameters (albedo,...) can be modified.
> 
> I expect a "table of modifications", which will overlay the base layer grid. Only the modified cells have to be given;
> 
> You can get the raster for baseline by this call:
> 
> https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_HW_GRID_DETAILS.1856/table/data
> 
> and you can update the modified table by POSTing them to this address:
> 
> https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/tab.CLY_HW_GRID_DETAILS_PROJ.1856/table/data

https://github.com/clarity-h2020/local-effects/issues/1#issuecomment-507159178

**Comment by p-a-s-c-a-l** [comment]
We would need an additional service / API that translates the JSON into some format (e.g. GeoJSON) that can be shown on the [IAO/AAO Map](https://github.com/clarity-h2020/map-component/issues/31). Furthermore, the respective [Data Package Resource](https://github.com/clarity-h2020/data-package/issues/17) has to be created and the example request / response URLs have to be [added to the Wiki](https://github.com/clarity-h2020/csis/issues/61).

Currently, this issue is on-hold since we first have to finish the general impact calculation.

**Comment by humerh** [comment]
Strategy for implementing a "simple" interface for applying "Adaptation strategies":

Denis proposed today at ZAMG, that the user should draw a (or more)  polygon in the map of the Study area and should apply a "Adaptation Strategy".
I find this is a very good solution, as it solves several problems:
- Nobody has to know something about "grid cells".
- Grid data need not be downloaded to CSIS, manipulated and uploaded again.
- It is a simple user step to draw a polygon and to add some "attributes to this polygon. No other interaction need to be done.
After this definition of the "Adaptation strategies" and starting of calculation this polygons have to be uploaded to Emikat and Emikat does the modification of the cell values themselve. This will also enable a consistent modification of "Land Usage" AND "parameters".

What we need for this calculation:
- We need the definition of the "Adaptation strategies" with the information:
--  How this adaptation influenses the the single Layers (Land usage) (eg. Albedo, Transmissivity,...)

 - The influenced AREAs can be calculated by EmiKat itself.

I think, this would simplyfy the user interface on CSIS side enormously!

What do you mean?

**Comment by p-a-s-c-a-l** [comment]
Interesting idea that could indeed make thins simpler. I'll think about it when we've resolved our most pressing issues.

**Comment by DenoBeno** [comment]
We have an even simpler possibility to start testing the application of adaptation options now: 

1. define adaptation options that can be used with EMIKAT (see https://github.com/clarity-h2020/csis/issues/77, https://github.com/clarity-h2020/data-package/issues/44) - this is something PLINIUS is working on.
2. Include these adaptation options in the screening data package. This is already possible on Drupal side, see https://csis.myclimateservice.eu/node/682/edit/step_2
3. Now the user can choose to include some of these adaptation options in the report, e.g. see https://csis.myclimateservice.eu/study/33/step/1515/view/table

So, we have a very simple way to indicate that some adaptation options should be applied to the whole project.  Once we have the new adaptation options from PLINIUS, EMIKAT should be able to use them and calculate new impact data.

Letting the users to apply the adaptation options selectively to parts of the project is nice to have but isn't a showstopper anymore...

**Comment by p-a-s-c-a-l** [comment]
done
