### ISSUE TITLE
Support Impact Scenarios [RA/IA API]

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/emikat#9]
This is related to the [implementation of Impact/Risk assessment model with EMIKAT](https://github.com/clarity-h2020/csis/issues/22). We need an API for triggering the calculation of a new impact scenario and for accessing the results. [Adaptation Scenarios](https://github.com/clarity-h2020/emikat/issues/8) are addressed later!

Triggering can be done by the [Scenario Selection UI](https://github.com/clarity-h2020/docker-drupal/issues/58) as discussed [here](https://github.com/clarity-h2020/data-package/issues/11#issuecomment-506661274).

- `$scenarioId` CSIS will sent the internal EMIKAT id (not the Drupal  UUID of the study).
- `$studyArea` this is probably not needed if the study has already been made know to EMIKAT via the [https://github.com/clarity-h2020/emikat/issues/6](initial study trigger)
- `$eventid[]` here CSIS probably just needs to send the ids of two events (baseline + future) selected by the user. 

Accessing the results is already possible as described in [this issue](https://github.com/clarity-h2020/csis/issues/22#issuecomment-442477185). We currently use them in the [Table Component](https://github.com/clarity-h2020/table-components/issues/4), the [Map Component](https://github.com/clarity-h2020/map-component/issues/30) and the [MCDA Tool](https://github.com/clarity-h2020/scenario-analysis/issues/13).

The respective [RA/IA Data Package Resource](https://github.com/clarity-h2020/data-package/issues/11) has to be updated accordingly and example request / response URLs (including WMS URLs for RA/IA maps) have to be [added to the Wiki](https://github.com/clarity-h2020/csis/issues/61).

**Comment by p-a-s-c-a-l** [comment]
**Example REST API URL**

https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2812/table/data

Questions:
- `2846` to be replaced with `$emikat_id`, but what about *view.2812*? Is it always the same view id?
- data format, e.g. # of damage classes, will change according to new impact model, right? When will it be available?

**Example WMS API URL**

https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity:view.2813&styles=DamageLevel1Q&bbox=4650500.0,1942000.0,4713000.0,1995500.0&width=768&height=657&srs=EPSG:3035&format=image%2Fgif&cql_filter=HAZARD_EVENT_ID=1

Questions:
- why no `$emikat_id` in WMS url?
- what about the *clarity:view.2813*?

**Comment by humerh** [comment]
You  need only replace the $emikat_id (for our example 2846).
The term "view.2813" or "clarity:view.2813" is an anonomized notation of a specific report. (report_Id). This report_id does not change, if you change the study (or EmiKat-Scenario).

**Comment by p-a-s-c-a-l** [comment]
> You need only replace the $emikat_id (for our example 2846).

Yes, but there's no `$emikat_id` in the **WMS** url.

**Comment by humerh** [comment]
There willl be the need to include also the $emikat_id in the WMS url.

We will update the definition of WMS-Call for Impact Layers also as a consequence of the big changes in model calculation.
Then I will provide a new link.

**Comment by p-a-s-c-a-l** [comment]
> The new Impact model is now implemented:
> 
> As WMS-Layers:
> 
> https://service.emikat.at/geoserver/clarity/wms?service=WMS&version=1.1.0&request=GetMap&layers=clarity%3Aview.2975&bbox=4672000.0%2C1979500.0%2C4687500.0%2C1988000.0&width=768&height=421&srs=EPSG%3A3035&format=image%2Fgif&CQL_FILTER=PROJECT_REF=1%20and%20PERIOD=%27Baseline%27%20AND%20RCP=%27Baseline%27%20AND%20FREQUENCE=%27Rare%27%20AND%20SZ_ID=2846&styles=DAMAGEQUANTITY
> 
> In this link you can adapt the follwing parameters:
> 
> PROJECT_REF=1 ... (for future selection of an alternate ADAPTATION variants)
> PERIOD='Baseline' ... (Alternatives are: '20110101-20401231', '20410101-20701231' and '20710101-21001231')
> RCP='Baseline' ... (Alternatives are: 'rcp26', 'rcp45' and 'rcp85')
> FREQUENCE='Rare' ... (Alternatives are: 'Occassional' or 'Frequent')
> 
> SZ_ID=2846 has to be set to the current $emikatID
> 
> The color schemas (STYLE colors) are currently fixed but not optimized !!!!
> 
> As JSON:
> https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/data?rownum=10000&filter=PROJECT_REF%3D1&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846
> 
> As CSV:
> https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/csv?rownum=10000&filter=PROJECT_REF%3D1&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846
> 
> or as GeoJSON
> https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2975/table/geojson?rownum=10000&filter=PROJECT_REF%3D1&filter=PERIOD%3D'Baseline'&filter=RCP%3D'Baseline'&filter=FREQUENCE%3D'Rare'&filter=SZ_ID%3D2846

**Comment by p-a-s-c-a-l** [comment]
@humerh Can you please check what's wrong with [this request](https://service.emikat.at/geoserver/clarity/wms?CQL_FILTER=STUDY_VARIANT=%27BASELINE%27%20and%20TIME_PERIOD=%2720110101-20401231%27%20AND%20EMISSIONS_SCENARIO=%27rcp45%27%20AND%20EVENT_FREQUENCY=%27Frequent%27%20AND%20SZ_ID=2846&service=WMS&request=GetMap&layers=clarity%3Aview.2975&styles=&format=image%2Fpng&transparent=true&version=1.1.1&leaflet=%5Bobject%20Object%5D&width=1536&height=1536&srs=EPSG%3A3857&bbox=1565430.3392804097,4950673.447974297,1624133.9770034251,5009377.085697314)?

Either the server is **extremely** slow or there is another problem, e.g. with from query parameters.

**Comment by p-a-s-c-a-l** [comment]
In order to re-enable the [Scenario Analysis Application](https://github.com/clarity-h2020/scenario-analysis/issues/15), we need a new view with the **sums for the whole study area**. We need furtherore the possibility to omit some or all filters to be able to compare across events, scenarios and / or time periods.

**Comment by humerh** [comment]
To get the total  number of affected people:

https://service.emikat.at/EmiKatTst/api/scenarios/2846/feature/view.2994/table/data

You can filter this query also by the usual filter flags:

**Comment by p-a-s-c-a-l** [comment]
Thanks! Could you also include the original damage probability? I know this can be calculated on client side, but I prefer to work with the original values calculated by the model.

**Comment by humerh** [comment]
How should I do this? I cannot sum up the propabilities, and they are different for each cell.
You can only do it again after building the sum:

Propability_StudyArea = EXPOSEDQUANTITY_StudyArea / DAMAGEQUANTITY_StudyArea.

**Comment by DenoBeno** [comment]
As discussed earlier today: is the per GRID_ID value of any use for the csis users?

In my opinion, the table view should sum over all grid cells and then show min/max/mean or mean/deviation values - for the whole project area.

Per grid data is only useful in combination with a  map.

**Comment by p-a-s-c-a-l** [comment]
We had this [already working](https://github.com/clarity-h2020/table-components/issues/4).

Once the results have been [validated](https://github.com/clarity-h2020/emikat/issues/24) and the data model has stabilised, we can update the [table component](https://github.com/clarity-h2020/table-components). I propose to wait for the specification of the flood impact result, so we don't have to redo this again for floods.

**Comment by p-a-s-c-a-l** [comment]
RA/IA API available and working.
